version: 2
updates:

  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "ci(github-actions): "
    labels:
      - "build"
      - "dependencies"
      - "github_actions"
    assignees:
      - "ginokent"
    reviewers:
      - "ginokent"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "build(go): "
    labels:
      - "build"
      - "dependencies"
      - "go"
    assignees:
      - "ginokent"
    reviewers:
      - "ginokent"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/implementations/zerolog/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "build(go): "
    labels:
      - "build"
      - "dependencies"
      - "go"
    assignees:
      - "ginokent"
    reviewers:
      - "ginokent"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/implementations/zap/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "build(go): "
    labels:
      - "build"
      - "dependencies"
      - "go"
    assignees:
      - "ginokent"
    reviewers:
      - "ginokent"
    groups:
      dependencies:
        patterns:
          - "*"
